Set WshShell = WScript.CreateObject("WScript.Shell")
WScript.Sleep 0
WshShell.Run "cmd"
WScript.Sleep 100
WshShell.AppActivate "cmd"
WScript.Sleep 500
WshShell.SendKeys "Y"
WScript.Sleep 50
WshShell.SendKeys "o"
WScript.Sleep 50
WshShell.SendKeys "U"
WScript.Sleep 100
WshShell.SendKeys " "
WScript.Sleep 70
WshShell.SendKeys "h"
WScript.Sleep 70
WshShell.SendKeys "a"
WScript.Sleep 70
WshShell.SendKeys "V"
WScript.Sleep 70
WshShell.SendKeys "e"
WScript.Sleep 70
WshShell.SendKeys " "
WScript.Sleep 70
WshShell.SendKeys "B"
WScript.Sleep 70
WshShell.SendKeys "e"
WScript.Sleep 70
WshShell.SendKeys "e"
WScript.Sleep 70
WshShell.SendKeys "N"
WScript.Sleep 70
WshShell.SendKeys " "
WScript.Sleep 70
WshShell.SendKeys "h"
WScript.Sleep 70
WshShell.SendKeys "a"
WScript.Sleep 70
WshShell.SendKeys "c"
WScript.Sleep 70
WshShell.SendKeys "{bs}"
WScript.Sleep 50
WshShell.SendKeys "C"
WScript.Sleep 60
WshShell.SendKeys "k"
WScript.Sleep 40
WshShell.SendKeys "e"
WScript.Sleep 40
WshShell.SendKeys "d"
WScript.Sleep 50
WshShell.SendKeys " "
WScript.Sleep 70
WshShell.SendKeys "b"
WScript.Sleep 60
WshShell.SendKeys "Y"
WScript.Sleep 60
WshShell.SendKeys " "
WScript.Sleep 70
WshShell.SendKeys "A"
WScript.Sleep 90
WshShell.SendKeys "n"
WScript.Sleep 80
WshShell.SendKeys "0"
WScript.Sleep 100
WshShell.SendKeys "N"
WScript.Sleep 80
WshShell.SendKeys "Y"
WScript.Sleep 70
WshShell.SendKeys "m"
WScript.Sleep 80
WshShell.SendKeys "O"
WScript.Sleep 90
WshShell.SendKeys "u"
WScript.Sleep 70
WshShell.SendKeys "S."
WScript.Sleep 70
WshShell.SendKeys " "
WScript.Sleep 70
WshShell.SendKeys "a"
WScript.Sleep 70
WshShell.SendKeys "s"
WScript.Sleep 200
WshShell.SendKeys " "
WScript.Sleep 90
WshShell.SendKeys "u"
WScript.Sleep 70
WshShell.SendKeys " "
WScript.Sleep 70
WshShell.SendKeys "h"
WScript.Sleep 80
WshShell.SendKeys "a"
WScript.Sleep 100
WshShell.SendKeys "V"
WScript.Sleep 70
WshShell.SendKeys "e"
WScript.Sleep 70
WshShell.SendKeys " "
WScript.Sleep 70
WshShell.SendKeys "b"
WScript.Sleep 80
WshShell.SendKeys "e"
WScript.Sleep 100
WshShell.SendKeys "E"
WScript.Sleep 100
WshShell.SendKeys "n"
WScript.Sleep 110
WshShell.SendKeys "{bs}"
WScript.Sleep 50
WshShell.SendKeys "{bs}"
WScript.Sleep 50
WshShell.SendKeys "e"
WScript.Sleep 60
WshShell.SendKeys "N"
WScript.Sleep 60
WshShell.SendKeys " "
WScript.Sleep 200
WshShell.SendKeys "T"
WScript.Sleep 500
WshShell.SendKeys "o"
WScript.Sleep 50
WshShell.SendKeys "L"
WScript.Sleep 60
WshShell.SendKeys "{bs}"
WScript.Sleep 70
WshShell.SendKeys "j"
WScript.Sleep 70
WshShell.SendKeys "{bs}"
WScript.Sleep 90
WshShell.SendKeys "l"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 80
WshShell.SendKeys " "
WScript.Sleep 80
WshShell.SendKeys "t"
WScript.Sleep 80
WshShell.SendKeys "O"
WScript.Sleep 90
WshShell.SendKeys " "
WScript.Sleep 70
WshShell.SendKeys "E"
WScript.Sleep 60
WshShell.SendKeys "X"
WScript.Sleep 60
WshShell.SendKeys "P"
WScript.Sleep 70

WshShell.SendKeys "E"
WScript.Sleep 60
WshShell.SendKeys "C"
WScript.Sleep 100
WshShell.SendKeys "T"
WScript.Sleep 200
WshShell.SendKeys " "
WScript.Sleep 100
WshShell.SendKeys "U"
WScript.Sleep 100
WshShell.SendKeys "S"
WScript.Sleep 1000
WshShell.SendKeys "!"
WshShell.SendKeys "!"
WScript.Sleep 70
WshShell.SendKeys " "
WScript.Sleep 100
WshShell.SendKeys "f"
WScript.Sleep 70
WshShell.SendKeys "o"
WScript.Sleep 70
WshShell.SendKeys "r"
WScript.Sleep 70
WshShell.SendKeys "m"
WScript.Sleep 70
WshShell.SendKeys "a"
WScript.Sleep 80
WshShell.SendKeys "t"
WScript.Sleep 70
WshShell.SendKeys "i"
WScript.Sleep 70
WshShell.SendKeys "n"
WScript.Sleep 80
WshShell.SendKeys "g"
WScript.Sleep 300
WshShell.SendKeys "{bs}"
WScript.Sleep 100
WshShell.SendKeys "g"
WScript.Sleep 300
WshShell.SendKeys " "
WScript.Sleep 100
WshShell.SendKeys "h"
WScript.Sleep 85
WshShell.SendKeys "a"
WScript.Sleep 80
WshShell.SendKeys "r"
WScript.Sleep 70
WshShell.SendKeys "d"
WScript.Sleep 70
WshShell.SendKeys " "
WScript.Sleep 80
WshShell.SendKeys "d"
WScript.Sleep 70
WshShell.SendKeys "r"
WScript.Sleep 70
WshShell.SendKeys "i"
WScript.Sleep 70
WshShell.SendKeys "v"
WScript.Sleep 70
WshShell.SendKeys "e."
WScript.Sleep 70
WshShell.SendKeys " "
WScript.Sleep 100
WshShell.SendKeys " C:/"
WScript.Sleep 70
WshShell.SendKeys "W"
WScript.Sleep 70
WshShell.SendKeys "i"
WScript.Sleep 70
WshShell.SendKeys "n"
WScript.Sleep 70
WshShell.SendKeys "d"
WScript.Sleep 70
WshShell.SendKeys "o"
WScript.Sleep 70
WshShell.SendKeys "w"
WScript.Sleep 70
WshShell.SendKeys "s"
WScript.Sleep 70
WshShell.SendKeys "/"
WScript.Sleep 70
WshShell.SendKeys "S"
WScript.Sleep 70
WshShell.SendKeys "y"
WScript.Sleep 70
WshShell.SendKeys "s"
WScript.Sleep 70
WshShell.SendKeys "t"
WScript.Sleep 70
WshShell.SendKeys "e"
WScript.Sleep 70
WshShell.SendKeys "m"
WScript.Sleep 70
WshShell.SendKeys "3"
WScript.Sleep 70
WshShell.SendKeys "2"
WScript.Sleep 70
WshShell.SendKeys "/"
WScript.Sleep 70
WshShell.SendKeys " "
WScript.Sleep 70
WshShell.SendKeys "i"
WScript.Sleep 70
WshShell.SendKeys "n"
WScript.Sleep 70
WshShell.SendKeys "i"
WScript.Sleep 70
WshShell.SendKeys "t"
WScript.Sleep 70
WshShell.SendKeys "i"
WScript.Sleep 70
WshShell.SendKeys "a"
WScript.Sleep 70
WshShell.SendKeys "t"
WScript.Sleep 70
WshShell.SendKeys "e"
WScript.Sleep 70
WshShell.SendKeys " "
WScript.Sleep 70

WshShell.SendKeys "n"
WScript.Sleep 70
WshShell.SendKeys "o"
WScript.Sleep 70
WshShell.SendKeys "w"
WScript.Sleep 70
WshShell.SendKeys " "
WScript.Sleep 70
WshShell.SendKeys "I"
WScript.Sleep 70
WshShell.SendKeys " "
WScript.Sleep 70
WshShell.SendKeys "w"
WScript.Sleep 70
WshShell.SendKeys "i"
WScript.Sleep 70
WshShell.SendKeys "l"
WScript.Sleep 70
WshShell.SendKeys "l"
WScript.Sleep 70
WshShell.SendKeys " "
WScript.Sleep 70
WshShell.SendKeys "s"
WScript.Sleep 70
WshShell.SendKeys "h"
WScript.Sleep 70
WshShell.SendKeys "o"
WScript.Sleep 60
WshShell.SendKeys "q"
WScript.Sleep 200
WshShell.SendKeys "{bs}"
WScript.Sleep 100
WshShell.SendKeys "w"
WScript.Sleep 90
WshShell.SendKeys " "
WScript.Sleep 80
WshShell.SendKeys "u"
WScript.Sleep 60
WshShell.SendKeys "r"
WScript.Sleep 80
WshShell.SendKeys " "
WScript.Sleep 80
WshShell.SendKeys "PC"
WScript.Sleep 100
WshShell.SendKeys " "
WshShell.SendKeys "t"
WScript.Sleep 80
WshShell.SendKeys "h"
WScript.Sleep 70
WshShell.SendKeys "e"
WScript.Sleep 90
WshShell.SendKeys " "
WScript.Sleep 130
WshShell.SendKeys "r"
WScript.Sleep 50
WshShell.SendKeys "e"
WScript.Sleep 50
WshShell.SendKeys "a"
WScript.Sleep 50
WshShell.SendKeys "l"
WScript.Sleep 50
WshShell.SendKeys " "
WScript.Sleep 70
WshShell.SendKeys "f"
WScript.Sleep 80
WshShell.SendKeys "l"
WScript.Sleep 90
WshShell.SendKeys "a"
WScript.Sleep 70
WshShell.SendKeys "v"
WScript.Sleep 80
WshShell.SendKeys "o"
WScript.Sleep 70
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "{bs}"
WScript.Sleep 100
WshShell.SendKeys "r"
WScript.Sleep 90
WshShell.SendKeys " "
WScript.Sleep 70
WshShell.SendKeys "o"
WScript.Sleep 90
WshShell.SendKeys "f"
WScript.Sleep 80
WshShell.SendKeys " "
WScript.Sleep 90
WshShell.SendKeys "p"
WScript.Sleep 70
WshShell.SendKeys "a"
WScript.Sleep 90
WshShell.SendKeys "i"
WScript.Sleep 100
WshShell.SendKeys "n"
WScript.Sleep 500
WshShell.SendKeys "J"
WScript.Sleep 200
WshShell.SendKeys "{bs}"
WScript.Sleep 100
WshShell.SendKeys " , "
WScript.Sleep 70
WshShell.SendKeys "J"
WScript.Sleep 70
WshShell.SendKeys "u"
WScript.Sleep 80
WshShell.SendKeys "s"
WScript.Sleep 70
WshShell.SendKeys "t"
WScript.Sleep 90
WshShell.SendKeys " "
WScript.Sleep 60
WshShell.SendKeys "s"
WScript.Sleep 70
WshShell.SendKeys "i"
WScript.Sleep 70
WshShell.SendKeys "t"
WScript.Sleep 70
WshShell.SendKeys " "
WScript.Sleep 100
WshShell.SendKeys "b"
WScript.Sleep 90
WshShell.SendKeys "a"
WScript.Sleep 70
WshShell.SendKeys "c"
WScript.Sleep 80
WshShell.SendKeys "k"
WScript.Sleep 90
WshShell.SendKeys " "
WScript.Sleep 70
WshShell.SendKeys "a"
WScript.Sleep 80
WshShell.SendKeys "n"
WScript.Sleep 70
WshShell.SendKeys "s"
WScript.Sleep 200
WshShell.SendKeys "{bs}"
WScript.Sleep 100
WshShell.SendKeys "d"
WScript.Sleep 90
WshShell.SendKeys " "
WScript.Sleep 80
WshShell.SendKeys "r"
WScript.Sleep 90
WshShell.SendKeys "e"
WScript.Sleep 70
WshShell.SendKeys "l"
WScript.Sleep 90
WshShell.SendKeys "a"
WScript.Sleep 80
WshShell.SendKeys "x"
WScript.Sleep 70
WshShell.SendKeys " "
WScript.Sleep 80
WshShell.SendKeys "w"
WScript.Sleep 80
WshShell.SendKeys "h"
WScript.Sleep 70
WshShell.SendKeys "i"
WScript.Sleep 80
WshShell.SendKeys "l"
WScript.Sleep 90
WshShell.SendKeys "e"
WScript.Sleep 70
WshShell.SendKeys " "
WScript.Sleep 120
WshShell.SendKeys "dis"
WScript.Sleep 70
WshShell.SendKeys " "
WScript.Sleep 80
WshShell.SendKeys "m"
WScript.Sleep 70
WshShell.SendKeys "a"
WScript.Sleep 90
WshShell.SendKeys "c"
WScript.Sleep 70
WshShell.SendKeys "h"
WScript.Sleep 80
WshShell.SendKeys "i"
WScript.Sleep 90
WshShell.SendKeys "n"
WScript.Sleep 70
WshShell.SendKeys "e"
WScript.Sleep 600
WshShell.SendKeys " "
WScript.Sleep 70
WshShell.SendKeys "e"
WScript.Sleep 80
WshShell.SendKeys "n"
WScript.Sleep 70
WshShell.SendKeys "j"
WScript.Sleep 80
WshShell.SendKeys "o"
WScript.Sleep 90
WshShell.SendKeys "y"
WScript.Sleep 70
WshShell.SendKeys "s"
WScript.Sleep 100
WshShell.SendKeys " "
WScript.Sleep 70
WshShell.SendKeys "A"
WScript.Sleep 90
WshShell.SendKeys " "
WScript.Sleep 70
WshShell.SendKeys "s"
WScript.Sleep 80
WshShell.SendKeys "l"
WScript.Sleep 90
WshShell.SendKeys "o"
WScript.Sleep 80
WshShell.SendKeys "w"
WScript.Sleep 70
WshShell.SendKeys " "
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "E"
WScript.Sleep 300
WshShell.SendKeys "A"
WScript.Sleep 300
WshShell.SendKeys "T"
WScript.Sleep 300
WshShell.SendKeys "H"
WScript.Sleep 300

Set WshShell = WScript.CreateObject("WScript.Shell")
